name: CICD

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_random-name-api:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'random-name-generator-api' }}
      run: |
        cd ./lucassarcanjo/random-funny-name-generator
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME